"""empty message

Revision ID: a03004cff78d
Revises: 3da0d5163390
Create Date: 2021-10-18 10:46:44.175961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a03004cff78d'
down_revision = '3da0d5163390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('total', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('progress', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'progress')
    op.drop_column('item', 'total')
    # ### end Alembic commands ###
